const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);let lastResult=null;
$$('.nav').forEach(b=>b.addEventListener('click',()=>{ $$('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.page').forEach(p=>p.classList.remove('active'));$('#'+b.dataset.page).classList.add('active');if(b.dataset.page==='audit')loadAudit();}));
function setStep(n,text){$('#s'+n).textContent=text;}
async function health(){try{const r=await fetch('/api/health');if(!r.ok)throw Error();$('#systemStatus').textContent='● SYSTEM ONLINE';}catch{$('#systemStatus').textContent='● OFFLINE';$('#systemStatus').style.color='#ff8795';}}
async function loadDemo(){const d=await (await fetch('/api/demo')).json();const f=$('#analysisForm');Object.entries(d).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v;});setStep(1,'Ready');setStep(2,'Ready');$('#formMessage').classList.add('hidden');}
$('#demoBtn').addEventListener('click',loadDemo);$('#scan').addEventListener('change',e=>$('#fileName').textContent=e.target.files[0]?.name||'No file selected');
$('#analysisForm').addEventListener('submit',async e=>{e.preventDefault();const msg=$('#formMessage');msg.classList.remove('hidden');msg.textContent='Validating evidence…';setStep(1,'Processing');setStep(2,'Validating');setStep(3,'Running');try{const r=await fetch('/api/analyze',{method:'POST',body:new FormData(e.target)});const data=await r.json();if(!r.ok)throw Error(data.detail||'Analysis failed');lastResult=data;renderResult(data);msg.textContent='Analysis completed. Human review is required before any action.';setStep(1,'Complete');setStep(2,'Complete');setStep(3,'Complete');setStep(4,'Required');setStep(5,'Blocked');$('#approvalCount').textContent='1';$('#riskCard').textContent=data.consensus.conflicts.length?'REVIEW':'REVIEW';$$('.nav')[2].click();loadAudit();}catch(err){msg.textContent=err.message;setStep(3,'Error');}});
function renderResult(d){let html=`<div><span class="tag">Audit ${d.audit_id.slice(0,8)}</span><p>${escapeHtml(d.consensus.reason)}</p></div>`;d.agents.forEach(a=>{html+=`<div class="agent"><h3>${escapeHtml(a.agent)} <span class="tag">${Math.round(a.confidence*100)}% confidence</span></h3><p>${escapeHtml(a.role)}</p><b>Findings</b><ul>${(a.findings.length?a.findings:['None']).map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul>${a.concerns.length?`<p class="danger">⚠ ${escapeHtml(a.concerns.join(' '))}</p>`:''}</div>`});html+='<h3>Cross-agent candidates</h3>';d.consensus.candidates.forEach(c=>html+=`<div class="candidate"><b>${escapeHtml(c.candidate)}</b> — support ${c.support}<br><small>${c.agents.join(', ')}</small></div>`);$('#analysisResult').innerHTML=html;$('#approvalResult').innerHTML=`<p><b>Audit:</b> ${d.audit_id}</p><p class="danger">Human review required. No autonomous diagnosis or external action is performed.</p><button class="btn danger" disabled>Action Locked</button>`;}
async function loadAudit(){const box=$('#auditList');try{const rows=await (await fetch('/api/audit?limit=50')).json();$('#logCount').textContent=rows.length;box.innerHTML=rows.length?rows.map(r=>`<div class="log-item"><b>${escapeHtml(r.patient_id)}</b><br><small>${escapeHtml(r.created_at)} · ${escapeHtml(r.audit_id)}</small></div>`).join(''):'<div class="empty">No audit events yet.</div>';}catch{box.innerHTML='<div class="empty">Could not load audit log.</div>';}}
$('#refreshAudit').addEventListener('click',loadAudit);function escapeHtml(x){return String(x??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}health();loadAudit();
